version: "3.3"

services:
  shifted:
    ports:
      - 3000:3000
    build:
      context: shifted
      dockerfile: Dockerfile
    volumes:
      - ./shifted:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next